using UniHub.Forum.Application.Abstractions;
using UniHub.Forum.Domain.Tags;
using UniHub.SharedKernel.CQRS;
using UniHub.SharedKernel.Results;

namespace UniHub.Forum.Application.Commands.CreateTag;

public sealed class CreateTagCommandHandler : ICommandHandler<CreateTagCommand, int>
{
    private readonly ITagRepository _tagRepository;

    public CreateTagCommandHandler(ITagRepository tagRepository)
    {
        _tagRepository = tagRepository;
    }

    public async Task<Result<int>> Handle(CreateTagCommand command, CancellationToken cancellationToken)
    {
        // Check if tag with same name already exists
        var existingTag = await _tagRepository.GetByNameAsync(command.Name, cancellationToken);
        if (existingTag != null)
        {
            return Result.Failure<int>(TagErrors.TagAlreadyExists);
        }

        var tagId = new TagId(0); // Will be generated by database
        var tagResult = Tag.Create(tagId, command.Name, command.Description);

        if (tagResult.IsFailure)
        {
            return Result.Failure<int>(tagResult.Error);
        }

        await _tagRepository.AddAsync(tagResult.Value, cancellationToken);

        return Result.Success(tagResult.Value.Id.Value);
    }
}
