import { Sparkles, ChevronDown, ChevronUp } from 'lucide-react'
import { useState } from 'react'
import type { SummarizePostResult } from '@features/assistant/api/assistant.api'

interface AISummaryCardProps {
  summary: SummarizePostResult | null
  isLoading: boolean
  error: string | null
  onRetry: () => void
}

export function AISummaryCard({ summary, isLoading, error, onRetry }: AISummaryCardProps) {
  const [isExpanded, setIsExpanded] = useState(false)

  if (!summary && !isLoading && !error) {
    return null
  }

  return (
    <div className="mt-8 rounded-xl border border-sky-200 bg-sky-50/50 p-6 overflow-hidden transition-all duration-200">
      <div className="flex items-start justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-sky-600" />
          <h2 className="text-[15px] font-semibold text-sky-900">AI Summary</h2>
          <span className="ml-2 rounded-full bg-sky-100 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-sky-700">
            Generated by AI
          </span>
        </div>
        {summary && (
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="flex items-center gap-1 rounded-full px-2 py-1 text-[12px] font-medium text-sky-700 hover:bg-sky-100 transition-colors"
          >
            {isExpanded ? (
              <>
                <ChevronUp className="h-4 w-4" /> Collapse
              </>
            ) : (
              <>
                <ChevronDown className="h-4 w-4" /> Expand
              </>
            )}
          </button>
        )}
      </div>

      <div className="mt-4">
        {isLoading && (
          <div className="space-y-3 animate-pulse">
            <div className="h-4 w-3/4 rounded bg-sky-200/50"></div>
            <div className="h-4 w-full rounded bg-sky-200/50"></div>
            <div className="h-4 w-5/6 rounded bg-sky-200/50"></div>
          </div>
        )}

        {error && !isLoading && (
          <div className="rounded-lg border border-red-200 bg-red-50 p-4">
            <p className="text-[13px] text-red-700">{error}</p>
            <button
              onClick={onRetry}
              className="mt-2 rounded bg-white px-3 py-1.5 text-[12px] font-medium text-red-700 shadow-sm border border-red-200 hover:bg-red-50"
            >
              Try Again
            </button>
          </div>
        )}

        {summary && !isLoading && !error && (
          <div className={`text-[14px] leading-relaxed text-slate-700 ${!isExpanded && summary.keyPoints?.length > 3 ? 'line-clamp-4' : ''}`}>
            {summary.summary && <p className="mb-3">{summary.summary}</p>}
            {summary.keyPoints && summary.keyPoints.length > 0 && (
              <ul className="list-inside list-disc space-y-1.5 marker:text-sky-400">
                {summary.keyPoints.slice(0, isExpanded ? undefined : 3).map((point, idx) => (
                  <li key={idx} className="pl-1">{point}</li>
                ))}
              </ul>
            )}
            {!isExpanded && summary.keyPoints && summary.keyPoints.length > 3 && (
              <p className="mt-2 text-[13px] font-medium text-sky-700 italic">...and {summary.keyPoints.length - 3} more points</p>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
