CREATE TABLE IF NOT EXISTS identity.user_blocks (
    blocker_user_id uuid NOT NULL,
    blocked_user_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL,
    PRIMARY KEY (blocker_user_id, blocked_user_id)
);
CREATE INDEX IF NOT EXISTS ix_user_blocks_blocked_user_id
    ON identity.user_blocks (blocked_user_id);

CREATE TABLE IF NOT EXISTS chat.conversation_mutes (
    user_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    is_muted boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (user_id, conversation_id)
);

CREATE TABLE IF NOT EXISTS chat.message_reports (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id uuid NOT NULL,
    conversation_id uuid NOT NULL,
    reporter_id uuid NOT NULL,
    reason integer NOT NULL,
    description character varying(2000),
    created_at timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_message_reports_reporter_message
    ON chat.message_reports (reporter_id, message_id);
CREATE INDEX IF NOT EXISTS ix_message_reports_message_id
    ON chat.message_reports (message_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260516120000_AddChatSafetyAndUserBlocks', '10.0.0')
ON CONFLICT DO NOTHING;
